services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: linux
    ports:
      - "5437:5432"
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 5675:5672
      - 15675:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq