spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/amqp
    username: postgres
    password: linux
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: 'update'

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq